version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: github-actions
    directory: /go-license-validator
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: github-actions
    directory: /npm-license-validator
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
